//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 02:05:00 PM CET 
//


package com.carcaret.trx.console.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.carcaret.trx.console.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TxStatisticsServiceResponderErrorCounter_QNAME = new QName("http://www.safelayer.com/TWS", "ResponderErrorCounter");
    private final static QName _TxStatisticsServiceSuccessServerAvg_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessServerAvg");
    private final static QName _TxStatisticsServiceSuccessClientMax_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessClientMax");
    private final static QName _TxStatisticsServiceSuccessCounter_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessCounter");
    private final static QName _TxStatisticsServiceSuccessClientMin_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessClientMin");
    private final static QName _TxStatisticsServiceRequesterErrorCounter_QNAME = new QName("http://www.safelayer.com/TWS", "RequesterErrorCounter");
    private final static QName _TxStatisticsServiceSuccessServerMax_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessServerMax");
    private final static QName _TxStatisticsServiceSuccessClientAvg_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessClientAvg");
    private final static QName _TxStatisticsServiceSuccessServerMin_QNAME = new QName("http://www.safelayer.com/TWS", "SuccessServerMin");
    private final static QName _TxStatisticsServiceLastRequest_QNAME = new QName("http://www.safelayer.com/TWS", "LastRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.carcaret.trx.console.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TxStatistics }
     * 
     */
    public TxStatistics createTxStatistics() {
        return new TxStatistics();
    }

    /**
     * Create an instance of {@link TxStatistics.Service }
     * 
     */
    public TxStatistics.Service createTxStatisticsService() {
        return new TxStatistics.Service();
    }

    /**
     * Create an instance of {@link TxStatistics.GlobalStats }
     * 
     */
    public TxStatistics.GlobalStats createTxStatisticsGlobalStats() {
        return new TxStatistics.GlobalStats();
    }

    /**
     * Create an instance of {@link TxStatistics.Service.LastRequest }
     * 
     */
    public TxStatistics.Service.LastRequest createTxStatisticsServiceLastRequest() {
        return new TxStatistics.Service.LastRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "ResponderErrorCounter", scope = TxStatistics.Service.class)
    public JAXBElement<Byte> createTxStatisticsServiceResponderErrorCounter(Byte value) {
        return new JAXBElement<Byte>(_TxStatisticsServiceResponderErrorCounter_QNAME, Byte.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessServerAvg", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceSuccessServerAvg(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceSuccessServerAvg_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessClientMax", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceSuccessClientMax(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceSuccessClientMax_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessCounter", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceSuccessCounter(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceSuccessCounter_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessClientMin", scope = TxStatistics.Service.class)
    public JAXBElement<Byte> createTxStatisticsServiceSuccessClientMin(Byte value) {
        return new JAXBElement<Byte>(_TxStatisticsServiceSuccessClientMin_QNAME, Byte.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "RequesterErrorCounter", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceRequesterErrorCounter(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceRequesterErrorCounter_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessServerMax", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceSuccessServerMax(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceSuccessServerMax_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessClientAvg", scope = TxStatistics.Service.class)
    public JAXBElement<Short> createTxStatisticsServiceSuccessClientAvg(Short value) {
        return new JAXBElement<Short>(_TxStatisticsServiceSuccessClientAvg_QNAME, Short.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "SuccessServerMin", scope = TxStatistics.Service.class)
    public JAXBElement<Byte> createTxStatisticsServiceSuccessServerMin(Byte value) {
        return new JAXBElement<Byte>(_TxStatisticsServiceSuccessServerMin_QNAME, Byte.class, TxStatistics.Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TxStatistics.Service.LastRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.safelayer.com/TWS", name = "LastRequest", scope = TxStatistics.Service.class)
    public JAXBElement<TxStatistics.Service.LastRequest> createTxStatisticsServiceLastRequest(TxStatistics.Service.LastRequest value) {
        return new JAXBElement<TxStatistics.Service.LastRequest>(_TxStatisticsServiceLastRequest_QNAME, TxStatistics.Service.LastRequest.class, TxStatistics.Service.class, value);
    }

}
