//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.09 at 02:52:13 PM CET 
//


package com.carcaret.trx.console.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.carcaret.trx.console.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.carcaret.trx.console.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TxStatistics }
     * 
     */
    public TxStatistics createTxStatistics() {
        return new TxStatistics();
    }

    /**
     * Create an instance of {@link TxStatistics.Service }
     * 
     */
    public TxStatistics.Service createTxStatisticsService() {
        return new TxStatistics.Service();
    }

    /**
     * Create an instance of {@link TxStatistics.GlobalStats }
     * 
     */
    public TxStatistics.GlobalStats createTxStatisticsGlobalStats() {
        return new TxStatistics.GlobalStats();
    }

    /**
     * Create an instance of {@link TxStatistics.Service.LastRequest }
     * 
     */
    public TxStatistics.Service.LastRequest createTxStatisticsServiceLastRequest() {
        return new TxStatistics.Service.LastRequest();
    }

}
