//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.09 at 02:52:13 PM CET 
//


package com.carcaret.trx.console.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlobalStats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StartAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SuccessClientAvg" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessClientMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessClientMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessServerAvg" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessServerMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessServerMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SuccessCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="RequesterErrorCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ResponderErrorCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LastRequest" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="FinishTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ClientProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ServerProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalStats",
    "service"
})
@XmlRootElement(name = "TxStatistics")
public class TxStatistics {

    @XmlElement(name = "GlobalStats", required = true)
    protected TxStatistics.GlobalStats globalStats;
    @XmlElement(name = "Service")
    protected List<TxStatistics.Service> service;

    /**
     * Gets the value of the globalStats property.
     * 
     * @return
     *     possible object is
     *     {@link TxStatistics.GlobalStats }
     *     
     */
    public TxStatistics.GlobalStats getGlobalStats() {
        return globalStats;
    }

    /**
     * Sets the value of the globalStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxStatistics.GlobalStats }
     *     
     */
    public void setGlobalStats(TxStatistics.GlobalStats value) {
        this.globalStats = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TxStatistics.Service }
     * 
     * 
     */
    public List<TxStatistics.Service> getService() {
        if (service == null) {
            service = new ArrayList<TxStatistics.Service>();
        }
        return this.service;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StartAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startAt"
    })
    public static class GlobalStats {

        @XmlElement(name = "StartAt", required = true)
        protected String startAt;

        /**
         * Gets the value of the startAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartAt() {
            return startAt;
        }

        /**
         * Sets the value of the startAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartAt(String value) {
            this.startAt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SuccessClientAvg" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessClientMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessClientMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessServerAvg" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessServerMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessServerMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SuccessCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="RequesterErrorCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ResponderErrorCounter" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LastRequest" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="FinishTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ClientProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ServerProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "successClientAvg",
        "successClientMin",
        "successClientMax",
        "successServerAvg",
        "successServerMin",
        "successServerMax",
        "successCounter",
        "requesterErrorCounter",
        "responderErrorCounter",
        "lastRequest"
    })
    public static class Service {

        @XmlElement(name = "SuccessClientAvg")
        protected int successClientAvg;
        @XmlElement(name = "SuccessClientMin")
        protected int successClientMin;
        @XmlElement(name = "SuccessClientMax")
        protected int successClientMax;
        @XmlElement(name = "SuccessServerAvg")
        protected int successServerAvg;
        @XmlElement(name = "SuccessServerMin")
        protected int successServerMin;
        @XmlElement(name = "SuccessServerMax")
        protected int successServerMax;
        @XmlElement(name = "SuccessCounter")
        protected int successCounter;
        @XmlElement(name = "RequesterErrorCounter")
        protected int requesterErrorCounter;
        @XmlElement(name = "ResponderErrorCounter")
        protected int responderErrorCounter;
        @XmlElement(name = "LastRequest")
        protected TxStatistics.Service.LastRequest lastRequest;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the successClientAvg property.
         * 
         */
        public int getSuccessClientAvg() {
            return successClientAvg;
        }

        /**
         * Sets the value of the successClientAvg property.
         * 
         */
        public void setSuccessClientAvg(int value) {
            this.successClientAvg = value;
        }

        /**
         * Gets the value of the successClientMin property.
         * 
         */
        public int getSuccessClientMin() {
            return successClientMin;
        }

        /**
         * Sets the value of the successClientMin property.
         * 
         */
        public void setSuccessClientMin(int value) {
            this.successClientMin = value;
        }

        /**
         * Gets the value of the successClientMax property.
         * 
         */
        public int getSuccessClientMax() {
            return successClientMax;
        }

        /**
         * Sets the value of the successClientMax property.
         * 
         */
        public void setSuccessClientMax(int value) {
            this.successClientMax = value;
        }

        /**
         * Gets the value of the successServerAvg property.
         * 
         */
        public int getSuccessServerAvg() {
            return successServerAvg;
        }

        /**
         * Sets the value of the successServerAvg property.
         * 
         */
        public void setSuccessServerAvg(int value) {
            this.successServerAvg = value;
        }

        /**
         * Gets the value of the successServerMin property.
         * 
         */
        public int getSuccessServerMin() {
            return successServerMin;
        }

        /**
         * Sets the value of the successServerMin property.
         * 
         */
        public void setSuccessServerMin(int value) {
            this.successServerMin = value;
        }

        /**
         * Gets the value of the successServerMax property.
         * 
         */
        public int getSuccessServerMax() {
            return successServerMax;
        }

        /**
         * Sets the value of the successServerMax property.
         * 
         */
        public void setSuccessServerMax(int value) {
            this.successServerMax = value;
        }

        /**
         * Gets the value of the successCounter property.
         * 
         */
        public int getSuccessCounter() {
            return successCounter;
        }

        /**
         * Sets the value of the successCounter property.
         * 
         */
        public void setSuccessCounter(int value) {
            this.successCounter = value;
        }

        /**
         * Gets the value of the requesterErrorCounter property.
         * 
         */
        public int getRequesterErrorCounter() {
            return requesterErrorCounter;
        }

        /**
         * Sets the value of the requesterErrorCounter property.
         * 
         */
        public void setRequesterErrorCounter(int value) {
            this.requesterErrorCounter = value;
        }

        /**
         * Gets the value of the responderErrorCounter property.
         * 
         */
        public int getResponderErrorCounter() {
            return responderErrorCounter;
        }

        /**
         * Sets the value of the responderErrorCounter property.
         * 
         */
        public void setResponderErrorCounter(int value) {
            this.responderErrorCounter = value;
        }

        /**
         * Gets the value of the lastRequest property.
         * 
         * @return
         *     possible object is
         *     {@link TxStatistics.Service.LastRequest }
         *     
         */
        public TxStatistics.Service.LastRequest getLastRequest() {
            return lastRequest;
        }

        /**
         * Sets the value of the lastRequest property.
         * 
         * @param value
         *     allowed object is
         *     {@link TxStatistics.Service.LastRequest }
         *     
         */
        public void setLastRequest(TxStatistics.Service.LastRequest value) {
            this.lastRequest = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="FinishTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ClientProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ServerProcessingTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "success",
            "finishTime",
            "result",
            "clientProcessingTime",
            "serverProcessingTime"
        })
        public static class LastRequest {

            @XmlElement(name = "Success")
            protected boolean success;
            @XmlElement(name = "FinishTime", required = true)
            protected String finishTime;
            @XmlElement(name = "Result", required = true)
            protected String result;
            @XmlElement(name = "ClientProcessingTime")
            protected int clientProcessingTime;
            @XmlElement(name = "ServerProcessingTime")
            protected int serverProcessingTime;

            /**
             * Gets the value of the success property.
             * 
             */
            public boolean isSuccess() {
                return success;
            }

            /**
             * Sets the value of the success property.
             * 
             */
            public void setSuccess(boolean value) {
                this.success = value;
            }

            /**
             * Gets the value of the finishTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFinishTime() {
                return finishTime;
            }

            /**
             * Sets the value of the finishTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFinishTime(String value) {
                this.finishTime = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResult(String value) {
                this.result = value;
            }

            /**
             * Gets the value of the clientProcessingTime property.
             * 
             */
            public int getClientProcessingTime() {
                return clientProcessingTime;
            }

            /**
             * Sets the value of the clientProcessingTime property.
             * 
             */
            public void setClientProcessingTime(int value) {
                this.clientProcessingTime = value;
            }

            /**
             * Gets the value of the serverProcessingTime property.
             * 
             */
            public int getServerProcessingTime() {
                return serverProcessingTime;
            }

            /**
             * Sets the value of the serverProcessingTime property.
             * 
             */
            public void setServerProcessingTime(int value) {
                this.serverProcessingTime = value;
            }

        }

    }

}
